### ISSUE TITLE
Using props in Sveltekit

### ISSUE THREAD

**Issue by TheGuyInApt42** [flekschas/svelte-simple-modal#55] opened 2021-12-06 18:13 UTC
I am having trouble using props in Sveltekit

`modal.set(bind(Popup, { name: 'custom name' }));` is not working.
I get error Uncaught TypeError: class constructors must be invoked with 'new'.

It works with the code below: 

`const modal = writable(null);

    function showModal() {
        modal.set(Popup);
    }`

**Comment by flekschas** [comment] 2021-12-07 14:15
Do you have an example repo that reproduces the error? It seems to be related to `bind()` but without further details it'll be hard to debug.

**Comment by flekschas** [comment] 2021-12-13 14:19
Thanks for putting the repo together. I'll try to look into the issue in the next few days.

**Comment by flekschas** [comment] 2021-12-20 08:44
Apologies for my late response. The issue with `bind()` was introduced in v1.1.1 and fixed in v1.1.2.

Besides that your import statement was wrong. It should be:

```
import Modal, { bind } from 'svelte-simple-modal';

...

modal.set(bind(Popup, { message: 'Test' }));
```

After installing the latest version (v1.1.3), I've tested it with your repo and it works as expected now.

Sorry for the glitch.

**Closed by flekschas** 2021-12-20 08:44 UTC

**Comment by TheGuyInApt42** [comment] 2021-12-20 21:24
No worries! I fixed the import statement but im still getting Typescript errors with 

`modal.set(bind(Popup, { message: 'Test' }));`

I get error Value of type 'typeof Modal' is not callable. Did you mean to include 'new'?

**Comment by nrikiji** [comment] 2022-02-15 06:30
same probrem too me.

**Comment by flekschas** [comment] 2022-02-15 13:32
> im still getting Typescript errors with

See https://github.com/flekschas/svelte-simple-modal/issues/58
