### ISSUE TITLE
Cannot respond to real-time theme color changes

### ISSUE THREAD

**Issue by guxuerui** [flekschas/svelte-simple-modal#104] opened 2023-07-11 06:46 UTC
When I try to make the `modal` background color change with the theme color, it always fails to update in real-time unless I refresh the page. What should I do?

My code: 

```js
let modalBg = 'rgba(255, 255, 255, 1)'
$: if ($currentTheme) {
  // currentTheme is a writable value, and I can get the right value after I change theme
  console.log('[src/routes/+layout.svelte:12] $currentTheme: ', $currentTheme)
  modalBg = $currentTheme === 'dark' ? 'rgba(31, 41, 55, 1)' : 'rgba(255, 255, 255, 1)'
  console.log('[src/routes/+layout.svelte:14] modalBg: ', modalBg)
}
```

```html
<Modal
  closeButton={true}
  unstyled={false}
  styleWindow={{ width: "80%", backgroundColor: modalBg }}
>
  <slot />
</Modal>
```

Can anyone provide me with some assistance?  Thank you very much.

**Comment by flekschas** [comment] 2024-01-10 01:37
You might need to recreate the style object to have its reference change when `modalBg` changes. E.g.:

```svelte
$: styleWindow = { width: "80%", backgroundColor: modalBg };
```

and assign `styleWindow` to the modal's `styleWindow`: `<Modal styleWindow={styleWindow}>...</Modal>`

**Comment by guxuerui** [comment] 2024-01-10 01:39
> You might need to recreate the style object to have its reference change when `modalBg` changes. E.g.:
> 
> ```svelte
> $: styleWindow = { width: "80%", backgroundColor: modalBg };
> ```
> 
> and assign `styleWindow` to the modal's `styleWindow`: `<Modal styleWindow={styleWindow}>...</Modal>`

OK，thanks for your reply~  I will try this again.

**Comment by flekschas** [comment] 2024-12-19 11:16
Closing this as I assume the issue is addressed. If it's not please let me know.

**Closed by flekschas** 2024-12-19 11:16 UTC
Labels: help wanted
