### ISSUE TITLE
Sapper returns 500 error

### ISSUE THREAD

**Issue by phr3nzy** [flekschas/svelte-simple-modal#6] opened 2019-12-30 10:59 UTC
I'm currently using this component on a production build, and it returns a 500 page for a few seconds with the current log: 

```
Error: <Modal> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:173:15)
    at /home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:241:5
    at Object.$$render (/home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:191:22)
    at /home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:395:36
    at Object.$$render (/home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:191:22)
    at Object.default (/home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:1283:86)
    at /home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:1108:37
    at Object.$$render (/home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:191:22)
    at /home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:1279:40
    at $$render (/home/phr3nzy/syodigital/sapper-frontend/__sapper__/dev/server/server.js:191:22)
```

It just shows it at the beginning of the page render and disappears, but when I build using `sapper export` it displays that the index.html page returns a 500 error. 

It works perfectly, but that error is inconvenient to users coming to the site. Thanks

PS: I am using the dedup fix. Same result.

**Comment by flekschas** [comment] 2019-12-31 10:07
Thanks for reporting. I am haven't used sapper's server so I can't give you direct advice. It'd be great if you could put together a minimal demo that shows the issue.

Apart from that:

- Which version of Sapper and simple-modal are you using?

> I'm currently using this component on a production build

Does that mean it's working fine in a development build?

> It just shows it at the beginning of the page render and disappears, but when I build using sapper export it displays that the index.html page returns a 500 error.

Does the 500 error stem from this error? I.e., does it go away if you remove simple-modal?

> It works perfectly, but that error is inconvenient to users coming to the site. Thanks

Are you saying everything works as expected but when you open the developer console you're seeing this error?

**Comment by phr3nzy** [comment] 2019-12-31 19:37
> Which version of Sapper and simple-modal are you using?

Both latest.

> Does that mean it's working fine in a development build?

It works everywhere perfectly, except for that one error that shows up for a split second when you first  load the app.

> Does the 500 error stem from this error? I.e., does it go away if you remove simple-modal?

Yeah after I remove it, it disappears. The curious thing is when I directly copy/paste the code from the Modal.svelte component from your lib, it works without the 500 error.

> Are you saying everything works as expected but when you open the developer console you're seeing this error?

Doesn't even show up on the dev console.

I'll try to create a repo to reproduce the bug, will have to wait a little though. Many thanks :)

**Comment by flekschas** [comment] 2020-01-03 10:42
Thanks for the clarification! That sounds really odd. This must be some weird glitch in the build process. Once we have a test repo I can take a look!

**Comment by pjarnfelt** [comment] 2020-01-21 14:37
I have the exact same problem except the server crashes with that error message for me.

**Comment by flekschas** [comment] 2020-01-21 15:30
> I have the exact same problem except the server crashes with that error message for me.

Without a test repository that reproduces the error it'll be hard to fix.

**Comment by flekschas** [comment] 2020-01-28 23:10
Closing this as it turns out that this behavior is expected as described in https://github.com/sveltejs/sapper-template#using-external-components

> It's essential that the bundler doesn't treat the package as an external dependency. You can either modify the external option under server in rollup.config.js or the externals option in webpack.config.js, or simply install the package to devDependencies rather than dependencies, which will cause it to get bundled (and therefore compiled) with your app:

```bash
npm install -D svelte-simple-modal
```

![Jan-28-2020 18-08-51](https://user-images.githubusercontent.com/932103/73313449-43e58980-41f9-11ea-9f37-036796e399a1.gif)

**Closed by flekschas** 2020-01-28 23:10 UTC
Labels: bug
